version: '1.0'

reverseProxy:

  config:                                         # Configuração principal
    listenAndServer: :8080                        # Servidor local. Formato: server:port
    outputConfig: true                            # Imprime a configuração inicial na saída padrão. Formato: true/false
    staticServer: true                            # Habilita um servidor de arquivos no servidor principal. Formato: true/false
    staticFolder:                                 # Configuração do servidor de arquivos
      - folder: /docker/static/                   # Caminho da pasta do servidor de arquivos
        serverPath: static                        # Path do servidor
      - folder: /docker/static/                   # Caminho da pasta do servidor de arquivos
        serverPath: static2                       # Path do servidor

  proxy:                                          # Servidor proxy. Redireciona o endereço para um novo servidor

    # Para rodar os exemplos abaixo, suba o container ghost, que instala um blog simples
    # docker run -d --name ghost-blog-1 -p 2368:2368 ghost
    blog:                                         # Nome a ser gravado no log para o serviço 1
      host: blog.localhost:8080                   # Endereço de entrada
      server:                                     # Lista de servidores
        - name: docker 1 - ok                     # nome a ser gravado no log:endereço
          host: http://localhost:2368             # host alternativo número 1
        - name: docker 2 - error                  # nome a ser gravado no log:endereço
          host: http://localhost:2369             # host alternativo número 2
        - name: docker 3 - error                  # nome a ser gravado no log:endereço
          host: http://localhost:2370             # host alternativo número 3

    # Para rodar os exemplos abaixo, suba o container ghost, que instala um blog simples
    # docker run -d --name ghost-blog-2 -p 2378:2368 ghost
    blog_2:                                       # Nome a ser gravado no log para o serviço 2
      host: blog2.localhost:8080                  # Endereço de entrada
      server:                                     # Lista de servidores
        - name: docker 1 - ok                     # nome a ser gravado no log:endereço
          host: http://localhost:2378             # host alternativo número 1
        - name: docker 2 - error                  # nome a ser gravado no log:endereço
          host: http://localhost:2379             # host alternativo número 2
        - name: docker 3 - error                  # nome a ser gravado no log:endereço
          host: http://localhost:2380             # host alternativo número 3
