# https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/
# https://golang.org/pkg/net/http/httputil/#example_ReverseProxy
version: 1.0

capibaribe:

  affluentRiverNameProject:

    listen: :8081
    debugServerEnable: false

    ssl:
      enabled: false

      # TLS 1.0 - 10
      # TLS 1.1 - 11
      # TLS 1.2 - 12
      # SSL 3.0 - 30
      version:
        min: 10
        max: 30
      certificate: /etc/nginx/company.com.crt
      certificateKey: /etc/nginx/company.com.key
      curvePreferences:
        - P256
        - P384
        - P521
        - X25519
      preferServerCipherSuites: false

      # A list of cipher suite IDs that are, or have been, implemented by this
      # package.
      #
      # Taken from https://www.iana.org/assignments/tls-parameters/tls-parameters.xml
      cipherSuites:
        - TLS_RSA_WITH_RC4_128_SHA
        - TLS_RSA_WITH_3DES_EDE_CBC_SHA
        - TLS_RSA_WITH_AES_128_CBC_SHA
        - TLS_RSA_WITH_AES_256_CBC_SHA
        - TLS_RSA_WITH_AES_128_CBC_SHA256
        - TLS_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
        - TLS_ECDHE_RSA_WITH_RC4_128_SHA
        - TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
        - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_FALLBACK_SCSV
      x509:
        certificate: /etc/nginx/company.com.crt
        certificateKey: /etc/nginx/company.com.key

    static:
      - filePath: /docker/static
        serverPath: static

    pygocentrus:
      enabled: true
      delay:
        rate: 0.1
        # time em uS
        min: 2000000
        max: 5000000
      dontRespond:
        rate: 0.1
          # time em uS
          min: 2000000
          max: 5000000
      changeLength: 0.0
      changeContent:
        changeRateMin: 0.0
        changeRateMax: 0.0
        changeBytesMin: 1
        changeBytesMax: 10
        rate: 0.1
      deleteContent: 0.1
      changeHeaders:
        - number: 500
          header:
            - key: Content-Type
              value: application/json
          rate: 0.0

    proxy:
      - ignorePort: true
        host: 127.0.0.1
        # roundRobin -              joga a carga para o próximo servidor
        # lowTimeResponseHeader -   procura o servidor com menor tempo de resposta inicial
        # lowTimeResponseLastByte - procura o servidor com menor tempo de resposta do último byte
        # random -                  joga a carga de forma aleatória
        # overLoad -                joga todas a carga para o primeiro servidor até o número máximo de conexões ser atingido
        # ipv4Hash -                000.000.*: de onde tiver o asterisco vai para um servidor
        # ipv6Hash -                lista de ips
        # hash -                    request_uri
#        bind:
#          - host: 127.0.0.1
#            ignorePort: true
        loadBalancing: roundRobin # roundRobin | lowTimeResponseHeader | lowTimeResponseLastByte | random | overLoad | ipv4Hash | ipv6Hash | hash
        path: /
        maxAttemptToRescueLoop: 10
        healthCheck:
          enabled: true
          # padrão: 5 segundos
          interval: 5000
          # numeros de falhas consecutivas para erro
          fails: 3
          # numeros de ok consecutivos para zerar falhas
          passes: 2
          # caminho de teste
          uri: /some/path
          # se 0 suspende para sempre
          # se !0 suspende por milesegundos
          suspendInterval: 30000
          match:
            status:
              - expReg: expreg
                value: 300
                in:
                  - min: 200
                    max: 299
                notIn:
                  - min: 200
                    max: 299
            header:
              - key: Content-Type
                value: text/html
            body:
              - expreg
        servers:
          - host: http://localhost:3000
            weight: 1
            overLoad: 1000000
          - host: http://localhost:3000
            weight: 1
            overLoad: 1000000
          - host: http://localhost:3000
            weight: 1
            overLoad: 1000000